Currency.create!(name: 'USD', country: 'United States of America', rate: 0.00)
Currency.create!(name: 'JPY', country: 'Japan', rate: 0.00)
Currency.create!(name: 'BGN', country: 'Bulgaria', rate: 0.00)
Currency.create!(name: 'CZK', country: 'Czech Republic', rate: 0.00)
Currency.create!(name: 'DKK', country: 'Denmark', rate: 0.00)
Currency.create!(name: 'GBP', country: 'United Kingdom', rate: 0.00)
Currency.create!(name: 'HUF', country: 'Hungary', rate: 0.00)
Currency.create!(name: 'PLN', country: 'Poland', rate: 0.00)
Currency.create!(name: 'RON', country: 'Romania', rate: 0.00)
Currency.create!(name: 'SEK', country: 'Sweden', rate: 0.00)
Currency.create!(name: 'CHF', country: 'Switzerland', rate: 0.00)
Currency.create!(name: 'NOK', country: 'Norway', rate: 0.00)
Currency.create!(name: 'HRK', country: 'Croatia', rate: 0.00)
Currency.create!(name: 'RUB', country: 'Russia', rate: 0.00)
Currency.create!(name: 'TRY', country: 'Turkey', rate: 0.00)
Currency.create!(name: 'AUD', country: 'Australia', rate: 0.00)
Currency.create!(name: 'BRL', country: 'Brazil', rate: 0.00)
Currency.create!(name: 'CAD', country: 'Canada', rate: 0.00)
Currency.create!(name: 'CNY', country: 'China', rate: 0.00)
Currency.create!(name: 'HKD', country: 'Hong Kong', rate: 0.00)
Currency.create!(name: 'IDR', country: 'Indonesia', rate: 0.00)
Currency.create!(name: 'ILS', country: 'Israel', rate: 0.00)
Currency.create!(name: 'KRW', country: 'South Korea', rate: 0.00)
Currency.create!(name: 'MXN', country: 'Mexico', rate: 0.00)
Currency.create!(name: 'MYR', country: 'Malaysia', rate: 0.00)
Currency.create!(name: 'NZD', country: 'New Zeland', rate: 0.00)
Currency.create!(name: 'PHP', country: 'Philippines', rate: 0.00)
Currency.create!(name: 'SGD', country: 'Singapore', rate: 0.00)
Currency.create!(name: 'THB', country: 'Thailand', rate: 0.00)
Currency.create!(name: 'ZAR', country: 'South Africa', rate: 0.00)
Currency.create!(name: 'INR', country: 'India', rate: 0.00)
